### ISSUE TITLE
notes.txt

### ISSUE THREAD

**Issue by cryptix** [ssbc/epidemic-broadcast-trees#25]
@dominictarr can you shed some light on the _uptodate_ness of the notes.txt? In some places it looks a bit like copy pasta and this makes me doubt is accuracy somehow..

I'm especially interested in the meaning of negative numbers (https://github.com/dominictarr/epidemic-broadcast-trees/blob/master/notes.txt#L45) since I've only saw `-1` in my experiemnts yet.

**Comment by dominictarr** [comment]
oh that is definitely not up to date. I think I only looked at that while I was figuring this out the first time. Will be working on docs and stuff. check the conditions branch for recent progress.
